### ISSUE TITLE
Update to image stream doesn't trigger deployment

### ISSUE THREAD

**Issue by f-w** [BCDevOps/issues-and-solutions#10]
My deployment config for `nodejs-mongodb-binary-src` contains following triggers:

```
triggers:
    -
      type: ImageChange
      imageChangeParams:
        containerNames:
          - nodejs-mongodb-binary-src
        from:
          kind: ImageStreamTag
          name: 'nodejs-mongodb-binary-src:latest'
        lastTriggeredImage: '172.16.156.227:5000/bcdev/nodejs-mongodb-binary-src@sha256:9f84fceea9229f742b2f9e944aa5139d94c5aedb54fe4e992c98646f39fda7e4'
    -
      type: ConfigChange
```

Here is what I get:
![image](https://cloud.githubusercontent.com/assets/12823994/14258974/b2a5addc-fa59-11e5-8300-e48173038697.png)

Image stream:
![image](https://cloud.githubusercontent.com/assets/12823994/14258991/ca48af7a-fa59-11e5-947c-f2650e5bb43a.png)
